Update wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -53,14 +53,7 @@ deploy-to-oke:
         server: $KUBERNETES_MASTER
         token: $KUBERNETES_TOKEN
         insecure-skip-tls-verify: true
-        command: create secret docker-registry ocir --docker-server=$DOCKER_REGISTRY --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --docker-email=${WERCKER_APPLICATION_OWNER_NAME}@mail.com --namespace=manish; echo create registry secret
-
-    - kubectl:
-        name: create TLS secret
-        server: $KUBERNETES_MASTER
-        token: $KUBERNETES_TOKEN
-        insecure-skip-tls-verify: true
-        command: create secret tls tls-secret --key $WERCKER_ROOT/tls.key --cert $WERCKER_ROOT/tls.crt --namespace=manish
+        command: create secret docker-registry ocir --docker-server=$DOCKER_REGISTRY --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --docker-email=${WERCKER_APPLICATION_OWNER_NAME}@mail.com --namespace=manish
         
     - kubectl:
         name: create deplyoment
@@ -79,22 +72,22 @@ deploy-to-oke:
         token: $KUBERNETES_TOKEN
         insecure-skip-tls-verify: true
         command: create -f $WERCKER_ROOT/ingress.yml --namespace=manish
-        
+
     - kubectl:
         name: get LoadBalancer public IP address
         server: $KUBERNETES_MASTER
         token: $KUBERNETES_TOKEN
         insecure-skip-tls-verify: true
-        command: get svc -o jsonpath='{.items[*].status.loadBalancer.ingress[*].ip}' --all-namespaces
+        command: get svc -o jsonpath='{.items[*].status.loadBalancer.ingress[*].ip}' --namespace=manish
 
-testapp:
+functional-test:
   steps:
     - script:
         name: Run and Test microservice
         code: |
               mkdir -p "/pipeline"
               node $WERCKER_ROOT/app.js &
-              sleep 10
+              sleep 5
               CREDITSCORE_URL=http://localhost:3000/creditscore
               echo 'Microservice URL=' $CREDITSCORE_URL
               if curl -X POST -H "Content-Type: application/json" -X POST -d '{"firstname":"John","lastname":"Doe","dateofbirth":"01/01/2015","ssn":"111223333"}' $CREDITSCORE_URL | grep "firstname"
@@ -105,18 +98,25 @@ testapp:
                   echo "Test failed"
                   exit -1
               fi
-              sleep 2
-              
+              sleep 1
 ui-functional-test:
   box:
-    id: peternagy/wercker-protractor-headless:chrome59-1
+    id: peternagy/chrome-protractor-headless-test:node9.2-chrome62
   steps:
     - script:
-        name: Run application and test UI
-        code: |
+        name: Run UI test
+        code: | 
               nohup node $WERCKER_ROOT/app.js > creditscoreapp.log &
-              echo 'Microservice URL to test: http://localhost:3000/creditscore'
+              echo 'Application URL to test: http://localhost:3000/creditscore'
               protractor $WERCKER_ROOT/test/protractor.conf.js
-              echo 'CreditScore app log:::'
+              exit_status=$?
+              echo 'CreditScore app server log :::START'
               cat creditscoreapp.log
-              echo 'CreditScore app log :::END'
+              echo 'CreditScore app server log :::END'
+              if [ $exit_status -eq 0 ]; then
+                echo "UI test passed"
+              else
+                echo "UI test failed"
+                exit -1
+              fi                
+              
